/**
 * DRAIS Editable Initials System
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 * 
 * Provides persistent, editable, class-wide synchronized initials for reports.
 * 
 * ARCHITECTURE:
 * - Initials stored in class_subjects.custom_initials
 * - Edit one subject in one class -> syncs to all learners in that class
 * - Override hierarchy: custom > template default > auto-generated
 * - Persists to database immediately
 * - Consistent across all report templates and exports
 */

import { getConnection } from '@/lib/db';

// ─────────────────────────────────────────────────────────────────────────────
// Type Definitions
// ─────────────────────────────────────────────────────────────────────────────

export interface InitialsConfig {
  classId: number;
  subjectId: number;
  schoolId: number;
  teacherId?: number;
  customInitials: string | null; // If set, overrides auto-generated
  templateDefaultInitials?: string; // From template config
  autoGeneratedInitials?: string; // Generated from teacher name
  displayInitials: string; // What actually shows in report
}

export interface InitialsUpdateRequest {
  schoolId: number;
  classId: number;
  subjectId: number;
  newInitials: string;
  updatedBy: number;
}

export interface InitialsHistory {
  id: string;
  classId: number;
  subjectId: number;
  previousInitials: string | null;
  newInitials: string;
  changedBy: number;
  changedAt: string;
  reason?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Fetch & Resolution
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Get initials configuration for a subject in a class
 * Resolves override hierarchy: custom > template default > auto-generated
 */
export async function getInitialsConfig(
  classId: number,
  subjectId: number,
  schoolId: number
): Promise<InitialsConfig> {
  const connection = await getConnection();

  try {
    // Get class_subjects record with all related data (join through classes for school_id)
    const [classSubjectsRows] = await connection.execute(
      `SELECT 
        cs.id,
        cs.class_id,
        cs.subject_id,
        cs.teacher_id,
        NULL AS custom_initials,
        CONCAT(UPPER(LEFT(p.first_name, 1)), UPPER(LEFT(p.last_name, 1))) AS auto_generated,
        p.first_name,
        p.last_name
       FROM class_subjects cs
       LEFT JOIN classes c ON cs.class_id = c.id
       LEFT JOIN staff s ON cs.teacher_id = s.id
       LEFT JOIN people p ON s.person_id = p.id
       WHERE cs.class_id = ? AND cs.subject_id = ? AND c.school_id = ?`,
      [classId, subjectId, schoolId]
    ) as any[];

    await connection.end();

    if (classSubjectsRows.length === 0) {
      throw new Error(`No class-subject assignment found for class ${classId}, subject ${subjectId}`);
    }

    const record = classSubjectsRows[0];

    // Resolve hierarchy: custom > auto-generated
    const displayInitials = record.custom_initials || record.auto_generated || 'N/A';

    return {
      classId,
      subjectId,
      schoolId,
      teacherId: record.teacher_id,
      customInitials: record.custom_initials,
      autoGeneratedInitials: record.auto_generated,
      displayInitials
    };
  } catch (error) {
    await connection.end();
    throw error;
  }
}

/**
 * Get all initials for a class
 * Used for report rendering to populate subject headers with initials
 */
export async function getClassInitials(
  classId: number,
  schoolId: number
): Promise<Map<number, InitialsConfig>> {
  const connection = await getConnection();

  try {
    const [rows] = await connection.execute(
      `SELECT 
        cs.class_id,
        cs.subject_id,
        cs.teacher_id,
        NULL AS custom_initials,
        CONCAT(UPPER(LEFT(p.first_name, 1)), UPPER(LEFT(p.last_name, 1))) AS auto_generated
       FROM class_subjects cs
       LEFT JOIN classes c ON cs.class_id = c.id
       LEFT JOIN staff s ON cs.teacher_id = s.id
       LEFT JOIN people p ON s.person_id = p.id
       WHERE cs.class_id = ? AND c.school_id = ?`,
      [classId, schoolId]
    ) as any[];

    await connection.end();

    const initialsMap = new Map<number, InitialsConfig>();

    for (const record of rows) {
      const displayInitials = record.custom_initials || record.auto_generated || 'N/A';
      initialsMap.set(record.subject_id, {
        classId,
        subjectId: record.subject_id,
        schoolId,
        teacherId: record.teacher_id,
        customInitials: record.custom_initials,
        autoGeneratedInitials: record.auto_generated,
        displayInitials
      });
    }

    return initialsMap;
  } catch (error) {
    await connection.end();
    throw error;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Update & Sync
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Update initials for a subject in a class
 * This syncs to ALL learners in that class for that subject (class-wide sync)
 * Persists to class_subjects.custom_initials
 */
export async function updateInitials(
  request: InitialsUpdateRequest
): Promise<{ success: boolean; affectedRecords: number }> {
  const connection = await getConnection();

  try {
    // Validation
    if (!request.newInitials || request.newInitials.trim().length === 0) {
      throw new Error('Initials cannot be empty');
    }

    if (request.newInitials.length > 10) {
      throw new Error('Initials must be 10 characters or less');
    }

    // Get previous initials for audit
    const [previousRows] = await connection.execute(
      `SELECT custom_initials FROM class_subjects
       WHERE class_id = ? AND subject_id = ?`,
      [request.classId, request.subjectId]
    ) as any[];

    const previousInitials = previousRows.length > 0 ? previousRows[0].custom_initials : null;

    // Update class_subjects record (single update - all learners in class get same initials)
    const result = await connection.execute(
      `UPDATE class_subjects 
       SET custom_initials = ?
       WHERE class_id = ? AND subject_id = ?`,
      [request.newInitials.trim(), request.classId, request.subjectId]
    ) as any[];

    const affectedRecords = result[0].affectedRows;

    // Log change for audit trail
    await connection.execute(
      `INSERT INTO initials_edit_history
       (class_id, subject_id, school_id, previous_initials, new_initials, changed_by, changed_at)
       VALUES (?, ?, ?, ?, ?, ?, NOW())`,
      [
        request.classId,
        request.subjectId,
        request.schoolId,
        previousInitials,
        request.newInitials.trim(),
        request.updatedBy
      ]
    );

    await connection.end();

    return {
      success: affectedRecords > 0,
      affectedRecords
    };
  } catch (error) {
    await connection.end();
    throw error;
  }
}

/**
 * Bulk update initials for multiple subjects in a class
 * Used for rapid editing workflows
 */
export async function bulkUpdateInitials(
  schoolId: number,
  classId: number,
  updates: Array<{ subjectId: number; initials: string }>,
  updatedBy: number
): Promise<{ success: boolean; totalUpdated: number }> {
  const connection = await getConnection();

  try {
    let totalUpdated = 0;

    for (const update of updates) {
      const [previousRows] = await connection.execute(
        `SELECT custom_initials FROM class_subjects
         WHERE class_id = ? AND subject_id = ?`,
        [classId, update.subjectId]
      ) as any[];

      const previousInitials = previousRows.length > 0 ? previousRows[0].custom_initials : null;

      const result = await connection.execute(
        `UPDATE class_subjects 
         SET custom_initials = ?
         WHERE class_id = ? AND subject_id = ?`,
        [update.initials.trim(), classId, update.subjectId]
      ) as any[];

      if (result[0].affectedRows > 0) {
        totalUpdated++;

        // Log change
        await connection.execute(
          `INSERT INTO initials_edit_history
           (class_id, subject_id, school_id, previous_initials, new_initials, changed_by, changed_at)
           VALUES (?, ?, ?, ?, ?, ?, NOW())`,
          [classId, update.subjectId, schoolId, previousInitials, update.initials.trim(), updatedBy]
        );
      }
    }

    await connection.end();

    return {
      success: totalUpdated > 0,
      totalUpdated
    };
  } catch (error) {
    await connection.end();
    throw error;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// History & Audit
// ─────────────────────────────────────────────────────────────────────────────

export async function getInitialsHistory(
  classId: number,
  limit: number = 50
): Promise<InitialsHistory[]> {
  const connection = await getConnection();

  try {
    const [rows] = await connection.execute(
      `SELECT 
        id,
        class_id as classId,
        subject_id as subjectId,
        previous_initials as previousInitials,
        new_initials as newInitials,
        changed_by as changedBy,
        changed_at as changedAt
       FROM initials_edit_history
       WHERE class_id = ?
       ORDER BY changed_at DESC
       LIMIT ?`,
      [classId, limit]
    ) as any[];

    await connection.end();

    return rows.map(r => ({
      id: r.id.toString(),
      classId: r.classId,
      subjectId: r.subjectId,
      previousInitials: r.previousInitials,
      newInitials: r.newInitials,
      changedBy: r.changedBy,
      changedAt: r.changedAt
    }));
  } catch (error) {
    await connection.end();
    throw error;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Report Integration
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Get display initials for a learner's report
 * Called during report generation to populate initials cells
 * Ensures consistency across all report formats
 */
export async function getLearnerReportInitials(
  studentId: number,
  classId: number,
  schoolId: number
): Promise<Map<number, string>> {
  // Get all subjects for the class
  const initialsMap = await getClassInitials(classId, schoolId);
  
  // Return display initials for each subject
  const reportInitials = new Map<number, string>();
  for (const [subjectId, config] of initialsMap) {
    reportInitials.set(subjectId, config.displayInitials);
  }

  return reportInitials;
}
