'use client';

/**
 * Class Initials Manager Component
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 * 
 * Full-featured UI for managing and editing initials for all subjects in a class.
 * Shows auto-generated vs custom initials with edit capability.
 */

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Loader2, RefreshCw, History } from 'lucide-react';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { EditableInitialsCell } from './EditableInitialsCell';

interface InitialsConfig {
  subjectId: number;
  classId: number;
  schoolId: number;
  teacherId?: number;
  customInitials: string | null;
  autoGeneratedInitials?: string;
  displayInitials: string;
}

interface ClassInitialsManagerProps {
  classId: number;
  className: string;
  onRefresh?: () => void;
}

export function ClassInitialsManager({
  classId,
  className,
  onRefresh
}: ClassInitialsManagerProps) {
  const [initials, setInitials] = useState<InitialsConfig[]>([]);
  const [history, setHistory] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showHistory, setShowHistory] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadInitials();
    if (showHistory) {
      loadHistory();
    }
  }, [classId, showHistory]);

  const loadInitials = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch(`/api/class-initials?classId=${classId}`);
      if (!response.ok) {
        throw new Error('Failed to load initials');
      }

      const data = await response.json();
      setInitials(data.initials || []);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const loadHistory = async () => {
    try {
      const response = await fetch(`/api/class-initials/history?classId=${classId}&limit=20`);
      if (!response.ok) {
        throw new Error('Failed to load history');
      }

      const data = await response.json();
      setHistory(data.history || []);
    } catch (err: any) {
      console.error('Failed to load history:', err.message);
    }
  };

  const handleSave = (subjectId: number, newInitials: string) => {
    // Update local state
    setInitials(prev =>
      prev.map(i =>
        i.subjectId === subjectId
          ? { ...i, customInitials: newInitials, displayInitials: newInitials }
          : i
      )
    );

    // Reload history if visible
    if (showHistory) {
      loadHistory();
    }

    onRefresh?.();
  };

  if (loading) {
    return (
      <Card>
        <CardContent className="pt-6 flex items-center justify-center gap-2">
          <Loader2 className="w-4 h-4 animate-spin" />
          Loading initials...
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Subject Initials - {className}</CardTitle>
        <CardDescription>
          Click on initials to edit them. Changes apply to the entire class.
        </CardDescription>
      </CardHeader>

      <CardContent className="space-y-4">
        {error && (
          <Alert variant="destructive">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {/* Initials Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {initials.map(item => (
            <div
              key={item.subjectId}
              className="p-3 border rounded-lg bg-gray-50 hover:bg-gray-100 transition-colors"
            >
              <div className="text-xs font-medium text-gray-600 mb-2">
                Subject
              </div>
              <div className="text-sm font-semibold mb-3">
                {/* Subject name would come from context - using generic label */}
                Subject {item.subjectId}
              </div>

              <div className="space-y-2">
                <div className="text-xs text-gray-600">
                  Current: {item.displayInitials}
                </div>

                {item.customInitials ? (
                  <div className="text-xs text-green-600">
                    ✓ Custom: {item.customInitials}
                  </div>
                ) : (
                  <div className="text-xs text-gray-500">
                    Auto-generated: {item.autoGeneratedInitials || 'N/A'}
                  </div>
                )}
              </div>

              <div className="mt-3">
                <EditableInitialsCell
                  classId={classId}
                  subjectId={item.subjectId}
                  currentInitials={item.displayInitials}
                  subjectName={`Subject ${item.subjectId}`}
                  onSave={(newInitials) => handleSave(item.subjectId, newInitials)}
                  className="w-full"
                />
              </div>
            </div>
          ))}
        </div>

        {initials.length === 0 && (
          <Alert>
            <AlertDescription>
              No subjects assigned to this class yet.
            </AlertDescription>
          </Alert>
        )}

        {/* Footer Actions */}
        <div className="flex gap-2 pt-4 border-t">
          <Button
            variant="outline"
            size="sm"
            onClick={() => loadInitials()}
          >
            <RefreshCw className="w-4 h-4 mr-2" />
            Refresh
          </Button>

          <Button
            variant="outline"
            size="sm"
            onClick={() => setShowHistory(!showHistory)}
          >
            <History className="w-4 h-4 mr-2" />
            {showHistory ? 'Hide' : 'Show'} History
          </Button>
        </div>

        {/* Edit History */}
        {showHistory && history.length > 0 && (
          <div className="mt-4 p-3 bg-gray-50 rounded border">
            <h4 className="font-semibold text-sm mb-3">Recent Changes</h4>
            <div className="space-y-2 max-h-48 overflow-y-auto">
              {history.map((entry, idx) => (
                <div key={idx} className="text-xs p-2 bg-white rounded border">
                  <div className="font-medium">
                    Changed at {new Date(entry.changedAt).toLocaleString()}
                  </div>
                  <div className="text-gray-600">
                    {entry.previousInitials || 'empty'} → {entry.newInitials}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
