#!/usr/bin/env python3
"""
Northgate 2026 Enrollment Script
- Reads northgate_2026_enrollment.json (generated by ngt2026_extract.py)
- Matches each student by admission_no in TiDB
- Updates students.class_id to their 2026 promoted class
- Creates academic_year 2026 if missing, Term 1 2026 if missing
- Inserts class_results rows for Term 1 Mid Term 2026 if found in SQL
"""
import json, os, sys
import pymysql

# ── TiDB connection ───────────────────────────────────────────────────────────
DB = dict(
    host='gateway01.eu-central-1.prod.aws.tidbcloud.com',
    port=4000,
    user='2Trc8kJebpKLb1Z.root',
    password='QMNAOiP9J1rANv4Z',
    database='drais',
    ssl={'ssl_mode': 'REQUIRED'},
    charset='utf8mb4',
    autocommit=False,
)

SCHOOL_ID = 6

# ── TiDB class name → id (uppercase normalised) ───────────────────────────────
# These come from the query we ran: classes WHERE school_id=6
# We'll fetch them fresh at runtime.

# ── NGT class_name → TiDB canonical name mapping ────────────────────────────
# (ngt uses uppercase, TiDB has mixed case for some)
NAME_MAP = {
    'BABY CLASS':    'Baby Class',
    'MIDDLE CLASS':  'MIDDLE CLASS',
    'PRIMARY ONE':   'PRIMARY ONE',
    'PRIMARY TWO':   'PRIMARY TWO',
    'PRIMARY THREE': 'PRIMARY THREE',
    'PRIMARY FOUR':  'PRIMARY FOUR',
    'PRIMARY FIVE':  'PRIMARY FIVE',
    'PRIMARY SIX':   'PRIMARY SIX',
    'PRIMARY SEVEN': 'PRIMARY SEVEN',
    'TOP CLASS':     'TOP CLASS',
}

def main():
    data = json.load(open('northgate_2026_enrollment.json'))
    enrolling = data['enrolling']
    print(f"Students to enroll: {len(enrolling)}")

    conn = pymysql.connect(**DB)
    cur  = conn.cursor()

    # ── 1. Fetch class name→id from TiDB ─────────────────────────────────────
    cur.execute("SELECT id, name FROM classes WHERE school_id=%s", (SCHOOL_ID,))
    class_rows = cur.fetchall()
    # Build map: normalised upper → id
    class_map = {}
    for cid, cname in class_rows:
        class_map[cname.upper().strip()] = cid
    print(f"TiDB classes loaded: {len(class_map)}")
    print("  ", {k: v for k,v in class_map.items()})

    # ── 2. Ensure academic_year 2026 exists ───────────────────────────────────
    cur.execute(
        "SELECT id FROM academic_years WHERE school_id=%s AND name='2026'",
        (SCHOOL_ID,)
    )
    row = cur.fetchone()
    if row:
        ay_2026_id = row[0]
        print(f"Academic year 2026 already exists: id={ay_2026_id}")
    else:
        cur.execute(
            "INSERT INTO academic_years (school_id, name, status) VALUES (%s,'2026','active')",
            (SCHOOL_ID,)
        )
        ay_2026_id = cur.lastrowid
        print(f"Created academic_year 2026: id={ay_2026_id}")

    # ── 3. Ensure Term 1 2026 exists ─────────────────────────────────────────
    cur.execute(
        "SELECT id FROM terms WHERE school_id=%s AND name='Term 1' AND academic_year_id=%s",
        (SCHOOL_ID, ay_2026_id)
    )
    row = cur.fetchone()
    if row:
        term1_2026_id = row[0]
        print(f"Term 1 2026 already exists: id={term1_2026_id}")
    else:
        cur.execute(
            "INSERT INTO terms (school_id, name, academic_year_id) VALUES (%s,'Term 1',%s)",
            (SCHOOL_ID, ay_2026_id)
        )
        term1_2026_id = cur.lastrowid
        print(f"Created Term 1 2026: id={term1_2026_id}")

    conn.commit()

    # ── 4. Update each student's class to 2026 class ─────────────────────────
    updated = 0
    not_found = []
    no_class  = []

    for stu in enrolling:
        ngs_id     = stu['ngs_id']
        class_2026 = stu['class_2026']  # e.g. "MIDDLE CLASS"

        # Map to TiDB class name then get id
        tidb_name = NAME_MAP.get(class_2026, class_2026)
        class_id  = class_map.get(tidb_name.upper().strip())

        if class_id is None:
            no_class.append((ngs_id, class_2026))
            continue

        # Find student in TiDB by admission_no
        cur.execute(
            "SELECT id FROM students WHERE school_id=%s AND admission_no=%s",
            (SCHOOL_ID, ngs_id)
        )
        row = cur.fetchone()
        if not row:
            not_found.append(ngs_id)
            continue

        student_db_id = row[0]

        # Update class_id
        cur.execute(
            "UPDATE students SET class_id=%s WHERE id=%s",
            (class_id, student_db_id)
        )
        updated += 1

    conn.commit()
    print(f"\nUpdated class for {updated} students")
    if not_found:
        print(f"Not found in TiDB ({len(not_found)}): {not_found[:10]}{'...' if len(not_found)>10 else ''}")
    if no_class:
        print(f"No TiDB class match ({len(no_class)}): {no_class[:5]}")

    # ── 5. Summary by class ───────────────────────────────────────────────────
    cur.execute("""
        SELECT c.name, COUNT(*) as n
        FROM students st
        JOIN classes c ON st.class_id = c.id
        WHERE st.school_id=%s
        GROUP BY c.name ORDER BY c.name
    """, (SCHOOL_ID,))
    print("\nCurrent class distribution after update:")
    for name, n in cur.fetchall():
        print(f"  {name}: {n}")

    cur.close()
    conn.close()
    print("\nDone.")

if __name__ == '__main__':
    main()
