-- TiDB Database Schema Export
-- Database: test (ibunbaz)
-- Exported: $(date)
-- Note: Schema only, no data

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;



receipts	CREATE TABLE `receipts` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `student_id` bigint DEFAULT NULL,\n  `payment_id` bigint DEFAULT NULL,\n  `receipt_no` varchar(60) NOT NULL,\n  `invoice_no` varchar(60) DEFAULT NULL,\n  `amount` decimal(14,2) NOT NULL,\n  `payment_method` varchar(30) DEFAULT NULL,\n  `reference` varchar(120) DEFAULT NULL,\n  `payer_name` varchar(150) DEFAULT NULL,\n  `payer_contact` varchar(50) DEFAULT NULL,\n  `notes` text DEFAULT NULL,\n  `file_url` varchar(255) DEFAULT NULL,\n  `qr_code_data` text DEFAULT NULL,\n  `invoice_url` varchar(255) DEFAULT NULL,\n  `metadata` json DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_receipts_school` (`school_id`),\n  KEY `idx_receipts_student` (`student_id`),\n  KEY `idx_receipts_no` (`receipt_no`),\n  KEY `idx_receipts_date` (`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Receipt tracking'


staff_attendance	CREATE TABLE `staff_attendance` (\n  `id` bigint NOT NULL,\n  `staff_id` bigint NOT NULL,\n  `date` date NOT NULL,\n  `status` varchar(20) DEFAULT 'present',\n  `notes` text COLLATE utf8_general_ci DEFAULT NULL,\n  `time_in` time DEFAULT NULL,\n  `time_out` time DEFAULT NULL,\n  `method` varchar(50) DEFAULT 'manual',\n  `marked_by` bigint DEFAULT NULL,\n  `marked_at` timestamp NULL DEFAULT NULL,\n  KEY `idx_staff_date` (`staff_id`,`date`),\n  KEY `idx_date` (`date`),\n  KEY `idx_status` (`status`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


student_next_of_kin	CREATE TABLE `student_next_of_kin` (\n  `id` bigint NOT NULL,\n  `student_id` bigint NOT NULL,\n  `sequence` tinyint NOT NULL,\n  `name` varchar(150) NOT NULL,\n  `address` varchar(255) DEFAULT NULL,\n  `occupation` varchar(120) DEFAULT NULL,\n  `contact` varchar(60) DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


attendance_reconciliation	CREATE TABLE `attendance_reconciliation` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `attendance_session_id` bigint DEFAULT NULL,\n  `student_id` bigint NOT NULL,\n  `manual_status` enum('present','absent','late','excused') COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `manual_marked_by` bigint DEFAULT NULL,\n  `manual_marked_at` timestamp NULL DEFAULT NULL,\n  `biometric_status` enum('present','absent','late') COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `biometric_marked_at` timestamp NULL DEFAULT NULL,\n  `reconciliation_status` enum('matched','conflict','biometric_only','manual_only') COLLATE utf8mb4_unicode_ci DEFAULT 'matched',\n  `conflict_resolution` enum('trust_biometric','trust_manual','manual_correction') COLLATE utf8mb4_unicode_ci DEFAULT 'trust_biometric',\n  `resolved_at` timestamp NULL DEFAULT NULL,\n  `resolved_by` bigint DEFAULT NULL,\n  `resolution_notes` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_session_student` (`attendance_session_id`,`student_id`),\n  KEY `idx_reconciliation_status` (`reconciliation_status`),\n  KEY `idx_student` (`student_id`),\n  KEY `idx_created_at` (`created_at`),\n  KEY `fk_reconciliation_school` (`school_id`),\n  CONSTRAINT `attendance_reconciliation_ibfk_1` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `attendance_reconciliation_ibfk_2` FOREIGN KEY (`attendance_session_id`) REFERENCES `attendance_sessions` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `attendance_reconciliation_ibfk_3` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Hybrid attendance reconciliation (manual vs biometric)'


waivers_discounts	CREATE TABLE `waivers_discounts` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `student_id` bigint NOT NULL,\n  `term_id` bigint NOT NULL,\n  `fee_item_id` bigint DEFAULT NULL,\n  `waiver_type` enum('full','partial') DEFAULT 'partial',\n  `discount_type` enum('percentage','fixed') DEFAULT 'fixed',\n  `amount` decimal(14,2) NOT NULL,\n  `reason` text NOT NULL,\n  `approved_by` bigint DEFAULT NULL,\n  `approved_at` timestamp NULL DEFAULT NULL,\n  `status` enum('pending','approved','rejected') DEFAULT 'pending',\n  `rejection_reason` text DEFAULT NULL,\n  `created_by` bigint DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_waivers_school` (`school_id`),\n  KEY `idx_waivers_student` (`student_id`),\n  KEY `idx_waivers_term` (`term_id`),\n  KEY `idx_waivers_status` (`status`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Fee waivers and discounts tracking'


device_access_logs	CREATE TABLE `device_access_logs` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `device_config_id` bigint NOT NULL,\n  `device_serial_number` varchar(100) DEFAULT NULL,\n  `event_timestamp` datetime NOT NULL,\n  `user_id` varchar(50) DEFAULT NULL,\n  `card_number` varchar(50) DEFAULT NULL,\n  `person_name` varchar(100) DEFAULT NULL,\n  `access_result` enum('granted','denied','unknown') DEFAULT 'unknown',\n  `device_event_id` varchar(50) DEFAULT NULL,\n  `device_event_type` varchar(100) DEFAULT NULL,\n  `raw_payload` json DEFAULT NULL,\n  `is_synced` tinyint(1) DEFAULT '1',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_device_config` (`device_config_id`),\n  KEY `idx_device_serial` (`device_serial_number`),\n  KEY `idx_event_timestamp` (`event_timestamp`),\n  KEY `idx_access_result` (`access_result`),\n  CONSTRAINT `device_access_logs_ibfk_1` FOREIGN KEY (`device_config_id`) REFERENCES `device_configs` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


device_sync_checkpoints	CREATE TABLE `device_sync_checkpoints` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `device_id` bigint NOT NULL,\n  `last_synced_device_time` timestamp NULL DEFAULT NULL,\n  `last_synced_remote_time` timestamp NULL DEFAULT NULL,\n  `total_logs_synced` bigint DEFAULT '0',\n  `failed_sync_attempts` int DEFAULT '0',\n  `is_syncing` tinyint(1) DEFAULT '0',\n  `sync_status` enum('success','partial','failed') COLLATE utf8mb4_unicode_ci DEFAULT 'success',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `uk_device` (`school_id`,`device_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


fingerprints	CREATE TABLE `fingerprints` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `student_id` bigint DEFAULT NULL,\n  `staff_id` bigint DEFAULT NULL,\n  `fingerprint_data` longblob NOT NULL,\n  `finger_position` varchar(20) DEFAULT NULL,\n  `quality_score` int DEFAULT NULL,\n  `enrollment_date` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `is_verified` tinyint(1) DEFAULT '0',\n  `verified_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_student` (`student_id`),\n  KEY `idx_staff` (`staff_id`),\n  KEY `idx_school` (`school_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


student_contacts	CREATE TABLE `student_contacts` (\n  `student_id` bigint NOT NULL,\n  `contact_id` bigint NOT NULL,\n  `relationship` varchar(50) DEFAULT NULL,\n  `is_primary` tinyint(1) DEFAULT '0'\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


attendance_sessions	CREATE TABLE `attendance_sessions` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `class_id` bigint NOT NULL,\n  `stream_id` bigint DEFAULT NULL,\n  `term_id` bigint DEFAULT NULL,\n  `academic_year_id` bigint DEFAULT NULL,\n  `subject_id` bigint DEFAULT NULL,\n  `teacher_id` bigint DEFAULT NULL,\n  `session_date` date NOT NULL,\n  `session_start_time` time DEFAULT NULL,\n  `session_end_time` time DEFAULT NULL,\n  `session_type` enum('morning_check','lesson','assembly','afternoon_check','custom') COLLATE utf8mb4_unicode_ci DEFAULT 'lesson',\n  `attendance_type` enum('manual','biometric','hybrid') COLLATE utf8mb4_unicode_ci DEFAULT 'manual',\n  `status` enum('draft','open','submitted','locked','finalized') COLLATE utf8mb4_unicode_ci DEFAULT 'draft',\n  `notes` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `submitted_at` timestamp NULL DEFAULT NULL,\n  `submitted_by` bigint DEFAULT NULL,\n  `finalized_at` timestamp NULL DEFAULT NULL,\n  `finalized_by` bigint DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_class_date` (`class_id`,`session_date`),\n  KEY `idx_status` (`status`),\n  KEY `idx_academic_year` (`academic_year_id`),\n  KEY `idx_teacher` (`teacher_id`),\n  KEY `idx_session_date` (`session_date`),\n  KEY `fk_attendance_sessions_school` (`school_id`),\n  KEY `fk_attendance_sessions_stream` (`stream_id`),\n  CONSTRAINT `attendance_sessions_ibfk_1` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `attendance_sessions_ibfk_2` FOREIGN KEY (`class_id`) REFERENCES `classes` (`id`),\n  CONSTRAINT `attendance_sessions_ibfk_3` FOREIGN KEY (`stream_id`) REFERENCES `streams` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `attendance_sessions_ibfk_4` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `attendance_sessions_ibfk_5` FOREIGN KEY (`class_id`) REFERENCES `classes` (`id`),\n  CONSTRAINT `attendance_sessions_ibfk_6` FOREIGN KEY (`stream_id`) REFERENCES `streams` (`id`) ON DELETE SET NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Attendance session tracking for class-level periods'


audit_log	CREATE TABLE `audit_log` (\n  `id` bigint NOT NULL,\n  `actor_user_id` bigint DEFAULT NULL,\n  `action` varchar(100) NOT NULL,\n  `entity_type` varchar(100) NOT NULL,\n  `entity_id` bigint DEFAULT NULL,\n  `changes_json` longtext DEFAULT NULL,\n  `ip` varchar(64) DEFAULT NULL,\n  `user_agent` varchar(255) DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


class_results	CREATE TABLE `class_results` (\n  `id` bigint NOT NULL,\n  `student_id` bigint NOT NULL,\n  `class_id` bigint NOT NULL,\n  `subject_id` bigint NOT NULL,\n  `term_id` bigint DEFAULT NULL,\n  `result_type_id` bigint NOT NULL,\n  `score` decimal(5,2) DEFAULT NULL,\n  `grade` varchar(10) DEFAULT NULL,\n  `remarks` text COLLATE utf8_general_ci DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


curriculums	CREATE TABLE `curriculums` (\n  `id` tinyint NOT NULL AUTO_INCREMENT,\n  `code` varchar(30) NOT NULL,\n  `name` varchar(100) NOT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=30003


parishes	CREATE TABLE `parishes` (\n  `id` bigint NOT NULL,\n  `subcounty_id` bigint NOT NULL,\n  `name` varchar(150) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


staff_salaries	CREATE TABLE `staff_salaries` (\n  `id` bigint NOT NULL,\n  `staff_id` bigint NOT NULL,\n  `month` year(4) DEFAULT NULL,\n  `period_month` tinyint DEFAULT NULL,\n  `definition_id` bigint NOT NULL,\n  `amount` decimal(14,2) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


classes	CREATE TABLE `classes` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `name` varchar(50) NOT NULL,\n  `curriculum_id` int DEFAULT NULL,\n  `class_level` int DEFAULT NULL,\n  `head_teacher_id` bigint DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=60005


contacts	CREATE TABLE `contacts` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `person_id` bigint NOT NULL,\n  `contact_type` varchar(30) NOT NULL,\n  `occupation` varchar(120) DEFAULT NULL,\n  `alive_status` varchar(20) DEFAULT NULL,\n  `date_of_death` date DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT NULL,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_person_id` (`person_id`),\n  CONSTRAINT `fk_1` FOREIGN KEY (`person_id`) REFERENCES `people` (`id`),\n  CONSTRAINT `fk_2` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30001


device_user_mappings	CREATE TABLE `device_user_mappings` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `device_id` bigint NOT NULL,\n  `student_id` bigint DEFAULT NULL,\n  `staff_id` bigint DEFAULT NULL,\n  `device_user_id` int NOT NULL COMMENT 'Device enrolled user ID (biometric ID)',\n  `status` enum('active','inactive','suspended') COLLATE utf8mb4_unicode_ci DEFAULT 'active',\n  `enrollment_status` enum('enrolled','pending','failed') COLLATE utf8mb4_unicode_ci DEFAULT 'enrolled',\n  `verified` tinyint(1) DEFAULT '0',\n  `mappings_sync_status` enum('pending','synced','failed') COLLATE utf8mb4_unicode_ci DEFAULT 'pending',\n  `last_synced_at` timestamp NULL DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `uk_school_device_user` (`school_id`,`device_user_id`),\n  UNIQUE KEY `uk_device_student` (`device_id`,`student_id`),\n  UNIQUE KEY `uk_device_staff` (`device_id`,`staff_id`),\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_device_id` (`device_id`),\n  KEY `idx_student_id` (`student_id`),\n  KEY `idx_staff_id` (`staff_id`),\n  KEY `idx_device_user_id` (`device_user_id`),\n  KEY `idx_status` (`status`),\n  KEY `idx_school_device` (`school_id`,`device_id`),\n  KEY `idx_school_student` (`school_id`,`student_id`),\n  KEY `idx_school_staff` (`school_id`,`staff_id`),\n  CONSTRAINT `fk_device_user_mappings_school` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_device_user_mappings_device` FOREIGN KEY (`device_id`) REFERENCES `biometric_devices` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_device_user_mappings_student` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_device_user_mappings_staff` FOREIGN KEY (`staff_id`) REFERENCES `staff` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Maps biometric device user IDs to students and staff members'


device_connection_history	CREATE TABLE `device_connection_history` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `device_config_id` bigint NOT NULL,\n  `connection_attempt_type` enum('test','scheduled_check','manual_reconnect','system_startup') DEFAULT 'test',\n  `status` enum('success','failed','timeout','unauthorized','unreachable','api_error') DEFAULT 'failed',\n  `http_status_code` int DEFAULT NULL,\n  `error_message` varchar(255) DEFAULT NULL,\n  `response_time_ms` int DEFAULT NULL,\n  `ip_address` varchar(50) DEFAULT NULL,\n  `port` int DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_device_config` (`device_config_id`),\n  KEY `idx_status` (`status`),\n  KEY `idx_created_at` (`created_at`),\n  CONSTRAINT `device_connection_history_ibfk_1` FOREIGN KEY (`device_config_id`) REFERENCES `device_configs` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


fee_payment_allocations	CREATE TABLE `fee_payment_allocations` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `payment_id` bigint NOT NULL,\n  `fee_item_id` bigint NOT NULL,\n  `allocated_amount` decimal(14,2) NOT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_payment` (`payment_id`),\n  KEY `idx_fee_item` (`fee_item_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


promotions	CREATE TABLE `promotions` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `student_id` bigint NOT NULL,\n  `from_class_id` bigint DEFAULT '0',\n  `to_class_id` bigint NOT NULL,\n  `from_academic_year_id` bigint DEFAULT NULL,\n  `to_academic_year_id` bigint DEFAULT NULL,\n  `promotion_status` enum('promoted','not_promoted','pending','deferred') DEFAULT 'pending',\n  `criteria_used` json DEFAULT NULL,\n  `remarks` text DEFAULT NULL,\n  `promoted_by` bigint DEFAULT NULL,\n  `approval_status` enum('pending','approved','rejected') DEFAULT 'pending',\n  `approved_by` bigint DEFAULT NULL,\n  `term_used` varchar(50) DEFAULT NULL,\n  `promotion_reason` enum('criteria_based','manual','appeal','correction') DEFAULT 'manual',\n  `prerequisite_met` tinyint(1) DEFAULT '1',\n  `additional_notes` text DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `unique_promotion_cycle` (`school_id`,`student_id`,`from_academic_year_id`),\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_student_id` (`student_id`),\n  KEY `idx_from_class` (`from_class_id`),\n  KEY `idx_to_class` (`to_class_id`),\n  KEY `idx_promotion_status` (`promotion_status`),\n  KEY `idx_approval_status` (`approval_status`),\n  KEY `idx_promoted_by` (`promoted_by`),\n  KEY `idx_created_at` (`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=6


report_card_metrics	CREATE TABLE `report_card_metrics` (\n  `report_card_id` bigint NOT NULL,\n  `total_score` decimal(7,2) DEFAULT NULL,\n  `average_score` decimal(5,2) DEFAULT NULL,\n  `min_score` decimal(5,2) DEFAULT NULL,\n  `max_score` decimal(5,2) DEFAULT NULL,\n  `position` int DEFAULT NULL,\n  `promoted` tinyint(1) DEFAULT '0',\n  `promotion_class_id` bigint DEFAULT NULL,\n  `computed_at` timestamp NULL DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


school_info	CREATE TABLE `school_info` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `school_name` varchar(255) NOT NULL,\n  `school_motto` varchar(255) DEFAULT NULL,\n  `school_address` text DEFAULT NULL,\n  `school_contact` varchar(20) DEFAULT NULL,\n  `school_email` varchar(255) DEFAULT NULL,\n  `school_logo` varchar(255) DEFAULT NULL,\n  `registration_number` varchar(100) DEFAULT NULL,\n  `website` varchar(255) DEFAULT NULL,\n  `founded_year` int DEFAULT NULL,\n  `principal_name` varchar(255) DEFAULT NULL,\n  `principal_email` varchar(255) DEFAULT NULL,\n  `principal_phone` varchar(20) DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `unique_school` (`school_id`),\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_created_at` (`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


school_settings	CREATE TABLE `school_settings` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `key_name` varchar(120) NOT NULL,\n  `value_text` text COLLATE utf8_general_ci DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


student_curriculums	CREATE TABLE `student_curriculums` (\n  `student_id` bigint NOT NULL,\n  `curriculum_id` tinyint NOT NULL,\n  `active` tinyint(1) DEFAULT '1',\n  `assigned_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


student_education_levels	CREATE TABLE `student_education_levels` (\n  `id` bigint NOT NULL,\n  `student_id` bigint NOT NULL,\n  `education_type` varchar(20) NOT NULL,\n  `level_name` varchar(120) NOT NULL,\n  `institution` varchar(150) DEFAULT NULL,\n  `year_completed` year(4) DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


exams	CREATE TABLE `exams` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `class_id` bigint NOT NULL,\n  `subject_id` bigint NOT NULL,\n  `term_id` bigint DEFAULT NULL,\n  `name` varchar(120) NOT NULL,\n  `body` varchar(50) DEFAULT NULL,\n  `date` date DEFAULT NULL,\n  `start_time` time DEFAULT NULL,\n  `end_time` time DEFAULT NULL,\n  `status` varchar(20) DEFAULT 'scheduled'\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


ledger_transactions	CREATE TABLE `ledger_transactions` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `transaction_no` varchar(50) NOT NULL,\n  `transaction_date` date DEFAULT NULL,\n  `transaction_type` enum('journal','payment','receipt','adjustment','transfer') DEFAULT 'journal',\n  `description` text DEFAULT NULL,\n  `reference_no` varchar(100) DEFAULT NULL,\n  `reference_type` varchar(50) DEFAULT NULL,\n  `reference_id` bigint DEFAULT NULL,\n  `total_amount` decimal(14,2) DEFAULT '0.00',\n  `status` enum('draft','posted','voided') DEFAULT 'draft',\n  `posted_by` bigint DEFAULT NULL,\n  `posted_at` timestamp NULL DEFAULT NULL,\n  `created_by` bigint DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_ltrx_school` (`school_id`),\n  KEY `idx_ltrx_no` (`transaction_no`),\n  KEY `idx_ltrx_date` (`transaction_date`),\n  KEY `idx_ltrx_status` (`status`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='General ledger transactions'


notification_preferences	CREATE TABLE `notification_preferences` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `user_id` bigint NOT NULL,\n  `school_id` bigint DEFAULT NULL,\n  `channel` varchar(50) NOT NULL,\n  `enabled` tinyint(1) DEFAULT '1',\n  `do_not_disturb` tinyint(1) DEFAULT '0',\n  `dnd_until` timestamp NULL DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `uq_user_channel` (`user_id`,`channel`),\n  KEY `idx_preferences_user` (`user_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='User notification preferences'


salary_payments	CREATE TABLE `salary_payments` (\n  `id` bigint NOT NULL,\n  `staff_id` bigint NOT NULL,\n  `wallet_id` bigint NOT NULL,\n  `amount` decimal(14,2) NOT NULL,\n  `method` varchar(30) DEFAULT NULL,\n  `reference` varchar(120) DEFAULT NULL,\n  `ledger_id` bigint DEFAULT NULL,\n  `paid_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


tahfiz_groups	CREATE TABLE `tahfiz_groups` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `name` varchar(100) NOT NULL,\n  `teacher_id` bigint NOT NULL,\n  `notes` text DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_teacher_id` (`teacher_id`),\n  KEY `idx_name` (`name`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


biometric_devices	CREATE TABLE `biometric_devices` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `device_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `device_code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `device_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'fingerprint',\n  `manufacturer` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `model` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `serial_number` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `location` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `mac_address` varchar(17) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `fingerprint_capacity` int DEFAULT '3000',\n  `enrollment_count` int DEFAULT '0',\n  `status` enum('active','inactive','maintenance','offline') COLLATE utf8mb4_unicode_ci DEFAULT 'active',\n  `last_sync_at` timestamp NULL DEFAULT NULL,\n  `sync_status` enum('synced','pending','failed') COLLATE utf8mb4_unicode_ci DEFAULT 'pending',\n  `sync_error_message` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `last_sync_record_count` int DEFAULT '0',\n  `battery_level` int DEFAULT NULL,\n  `storage_used_percent` decimal(5,2) DEFAULT NULL,\n  `is_master` tinyint(1) DEFAULT '0',\n  `api_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `api_secret` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `device_code` (`device_code`),\n  UNIQUE KEY `serial_number` (`serial_number`),\n  UNIQUE KEY `unique_device_code` (`device_code`),\n  UNIQUE KEY `unique_serial` (`serial_number`),\n  KEY `idx_school` (`school_id`),\n  KEY `idx_status` (`status`),\n  KEY `idx_sync_status` (`sync_status`),\n  KEY `idx_school_status` (`school_id`,`status`),\n  CONSTRAINT `biometric_devices_ibfk_1` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Biometric device management and tracking'


branches	CREATE TABLE `branches` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `name` varchar(150) NOT NULL,\n  `phone` varchar(30) DEFAULT NULL,\n  `email` varchar(150) DEFAULT NULL,\n  `address` text COLLATE utf8_general_ci DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT NULL,\n  `deleted_at` timestamp NULL DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


device_users	CREATE TABLE `device_users` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `device_user_id` int NOT NULL,\n  `person_type` enum('student','teacher') COLLATE utf8mb4_unicode_ci NOT NULL,\n  `person_id` bigint NOT NULL,\n  `device_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `is_enrolled` tinyint(1) DEFAULT '1',\n  `enrollment_date` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `unenrollment_date` timestamp NULL DEFAULT NULL,\n  `biometric_quality` int DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `uk_school_device_user` (`school_id`,`device_user_id`),\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_person` (`person_type`,`person_id`),\n  KEY `idx_is_enrolled` (`is_enrolled`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


finance_categories	CREATE TABLE `finance_categories` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `type` varchar(20) NOT NULL,\n  `category_type` enum('income','expense','transfer') DEFAULT 'income',\n  `parent_id` bigint DEFAULT NULL,\n  `is_system` tinyint(1) DEFAULT '0',\n  `color` varchar(20) DEFAULT '#3B82F6',\n  `icon` varchar(50) DEFAULT 'DollarSign',\n  `is_active` tinyint(1) DEFAULT '1',\n  `name` varchar(120) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


nationalities	CREATE TABLE `nationalities` (\n  `id` int NOT NULL,\n  `code` varchar(3) NOT NULL,\n  `name` varchar(100) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


password_resets	CREATE TABLE `password_resets` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `user_id` bigint NOT NULL,\n  `token` varchar(255) NOT NULL,\n  `expires_at` timestamp NOT NULL,\n  `used` tinyint(1) DEFAULT '0',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `token` (`token`),\n  KEY `idx_user_id` (`user_id`),\n  KEY `idx_token` (`token`),\n  KEY `idx_expires` (`expires_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


subjects	CREATE TABLE `subjects` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `name` varchar(120) NOT NULL,\n  `code` varchar(20) DEFAULT NULL,\n  `subject_type` varchar(20) DEFAULT 'core'\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


counties	CREATE TABLE `counties` (\n  `id` bigint NOT NULL,\n  `district_id` bigint NOT NULL,\n  `name` varchar(150) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


department_workplans	CREATE TABLE `department_workplans` (\n  `id` bigint NOT NULL,\n  `department_id` bigint NOT NULL,\n  `title` varchar(200) NOT NULL,\n  `description` text COLLATE utf8_general_ci DEFAULT NULL,\n  `start_datetime` datetime DEFAULT NULL,\n  `end_datetime` datetime DEFAULT NULL,\n  `status` varchar(20) DEFAULT 'pending',\n  `created_by` bigint DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


document_types	CREATE TABLE `document_types` (\n  `id` bigint NOT NULL,\n  `code` varchar(60) NOT NULL,\n  `label` varchar(120) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


financial_reports	CREATE TABLE `financial_reports` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `report_type` enum('income_statement','balance_sheet','cash_flow','fee_collection','expense_analysis','budget_variance') DEFAULT 'income_statement',\n  `report_name` varchar(150) DEFAULT NULL,\n  `report_period` enum('daily','weekly','monthly','term','yearly') DEFAULT 'monthly',\n  `start_date` date DEFAULT NULL,\n  `end_date` date DEFAULT NULL,\n  `academic_year_id` bigint DEFAULT NULL,\n  `term_id` bigint DEFAULT NULL,\n  `report_data` json DEFAULT NULL,\n  `generated_by` bigint DEFAULT NULL,\n  `generated_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `status` enum('generating','completed','failed') DEFAULT 'completed',\n  `error_message` text DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_frep_school` (`school_id`),\n  KEY `idx_frep_type` (`report_type`),\n  KEY `idx_frep_period` (`start_date`,`end_date`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Financial reports storage'


report_cards	CREATE TABLE `report_cards` (\n  `id` bigint NOT NULL,\n  `student_id` bigint NOT NULL,\n  `term_id` bigint NOT NULL,\n  `overall_grade` varchar(10) DEFAULT NULL,\n  `class_teacher_comment` text COLLATE utf8_general_ci DEFAULT NULL,\n  `headteacher_comment` text COLLATE utf8_general_ci DEFAULT NULL,\n  `dos_comment` text COLLATE utf8_general_ci DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


results	CREATE TABLE `results` (\n  `id` bigint NOT NULL,\n  `exam_id` bigint NOT NULL,\n  `student_id` bigint NOT NULL,\n  `score` decimal(5,2) DEFAULT NULL,\n  `grade` varchar(5) DEFAULT NULL,\n  `remarks` text COLLATE utf8_general_ci DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


schools	CREATE TABLE `schools` (\n  `id` bigint NOT NULL,\n  `name` varchar(150) NOT NULL,\n  `legal_name` varchar(200) DEFAULT NULL,\n  `short_code` varchar(50) DEFAULT NULL,\n  `email` varchar(150) DEFAULT NULL,\n  `phone` varchar(30) DEFAULT NULL,\n  `currency` varchar(10) DEFAULT 'UGX',\n  `address` text COLLATE utf8_general_ci DEFAULT NULL,\n  `logo_url` varchar(255) DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT NULL,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


staff	CREATE TABLE `staff` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `branch_id` bigint DEFAULT '1',\n  `person_id` bigint NOT NULL,\n  `staff_no` varchar(50) DEFAULT NULL,\n  `department_id` bigint DEFAULT NULL,\n  `role_id` bigint DEFAULT NULL,\n  `position` varchar(100) DEFAULT NULL,\n  `employment_type` enum('permanent','contract','volunteer','part-time') DEFAULT 'permanent',\n  `qualification` varchar(255) DEFAULT NULL,\n  `experience_years` int DEFAULT '0',\n  `hire_date` date DEFAULT NULL,\n  `salary` decimal(14,2) DEFAULT NULL,\n  `bank_name` varchar(150) DEFAULT NULL,\n  `bank_account_no` varchar(100) DEFAULT NULL,\n  `nssf_no` varchar(100) DEFAULT NULL,\n  `tin_no` varchar(100) DEFAULT NULL,\n  `status` varchar(20) DEFAULT 'active',\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=90013


tahfiz_results	CREATE TABLE `tahfiz_results` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `student_id` bigint NOT NULL,\n  `group_id` bigint DEFAULT NULL,\n  `term_id` bigint DEFAULT NULL,\n  `academic_year_id` bigint DEFAULT NULL,\n  `portion_id` bigint DEFAULT NULL,\n  `result_date` date DEFAULT NULL,\n  `pages_memorized` int DEFAULT '0',\n  `pages_reviewed` int DEFAULT '0',\n  `juz_completed` int DEFAULT '0',\n  `memorization_percentage` decimal(5,2) DEFAULT '0.00',\n  `accuracy_score` decimal(5,2) DEFAULT '0.00',\n  `overall_score` decimal(5,2) DEFAULT '0.00',\n  `remarks` text DEFAULT NULL,\n  `recorded_by` bigint DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school_student` (`school_id`,`student_id`),\n  KEY `idx_result_date` (`result_date`),\n  KEY `idx_term_academic_year` (`term_id`,`academic_year_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


v_today_arrivals	CREATE ALGORITHM=UNDEFINED DEFINER=`2qzYvPUSbNa3RNc.root`@`%` SQL SECURITY DEFINER VIEW `v_today_arrivals` (`school_id`, `person_id`, `student_id_number`, `student_name`, `class_name`, `status`, `first_arrival_time`, `device_location`, `arrival_status`, `arrival_device_id`) AS SELECT 1 AS `school_id`,1 AS `person_id`,1 AS `student_id_number`,1 AS `student_name`,1 AS `class_name`,1 AS `status`,1 AS `first_arrival_time`,1 AS `device_location`,1 AS `arrival_status`,1 AS `arrival_device_id`	utf8mb4	utf8mb4_bin


device_sync_logs	CREATE TABLE `device_sync_logs` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `device_id` bigint NOT NULL,\n  `sync_type` enum('attendance_download','fingerprint_upload','logs_fetch','device_sync') COLLATE utf8mb4_unicode_ci DEFAULT 'attendance_download',\n  `sync_direction` enum('pull','push','bidirectional') COLLATE utf8mb4_unicode_ci DEFAULT 'pull',\n  `status` enum('pending','in_progress','success','partial_success','failed') COLLATE utf8mb4_unicode_ci DEFAULT 'pending',\n  `records_processed` int DEFAULT '0',\n  `records_synced` int DEFAULT '0',\n  `records_failed` int DEFAULT '0',\n  `error_message` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `details_json` json DEFAULT NULL,\n  `started_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `completed_at` timestamp NULL DEFAULT NULL,\n  `duration_seconds` int DEFAULT NULL,\n  `initiated_by` bigint DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_device` (`device_id`),\n  KEY `idx_started_at` (`started_at`),\n  KEY `idx_status` (`status`),\n  KEY `idx_sync_type` (`sync_type`),\n  KEY `fk_sync_logs_school` (`school_id`),\n  CONSTRAINT `device_sync_logs_ibfk_1` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `device_sync_logs_ibfk_2` FOREIGN KEY (`device_id`) REFERENCES `biometric_devices` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Device synchronization operation logs'


ledger_accounts	CREATE TABLE `ledger_accounts` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `account_code` varchar(50) NOT NULL,\n  `account_name` varchar(150) NOT NULL,\n  `account_type` enum('asset','liability','income','expense','equity') DEFAULT 'asset',\n  `account_subtype` varchar(50) DEFAULT NULL,\n  `parent_id` bigint DEFAULT NULL,\n  `balance_type` enum('debit','credit') DEFAULT 'debit',\n  `opening_balance` decimal(14,2) DEFAULT '0.00',\n  `current_balance` decimal(14,2) DEFAULT '0.00',\n  `currency` varchar(10) DEFAULT 'TZS',\n  `is_active` tinyint(1) DEFAULT '1',\n  `is_system` tinyint(1) DEFAULT '0',\n  `description` text DEFAULT NULL,\n  `created_by` bigint DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_ledger_school` (`school_id`),\n  KEY `idx_ledger_code` (`account_code`),\n  KEY `idx_ledger_type` (`account_type`),\n  KEY `idx_ledger_parent` (`parent_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='General ledger accounts'


student_attendance	CREATE TABLE `student_attendance` (\n  `id` bigint NOT NULL,\n  `student_id` bigint NOT NULL,\n  `date` date NOT NULL,\n  `status` varchar(20) DEFAULT 'present',\n  `method` varchar(50) DEFAULT 'manual',\n  `time_in` time DEFAULT NULL,\n  `time_out` time DEFAULT NULL,\n  `notes` text COLLATE utf8_general_ci DEFAULT NULL,\n  `marked_at` timestamp NULL DEFAULT NULL,\n  `marked_by` int DEFAULT NULL,\n  `attendance_session_id` bigint DEFAULT NULL COMMENT 'Link to attendance session',\n  `term_id` bigint DEFAULT NULL COMMENT 'Academic term',\n  `academic_year_id` bigint DEFAULT NULL COMMENT 'Academic year',\n  `stream_id` bigint DEFAULT NULL COMMENT 'Student stream/section',\n  `subject_id` bigint DEFAULT NULL COMMENT 'Subject (if applicable)',\n  `teacher_id` bigint DEFAULT NULL COMMENT 'Teacher who took attendance',\n  `device_id` bigint DEFAULT NULL COMMENT 'Biometric device ID',\n  `biometric_timestamp` timestamp NULL DEFAULT NULL COMMENT 'Biometric capture timestamp',\n  `confidence_score` decimal(5,2) DEFAULT NULL COMMENT 'Biometric confidence score',\n  `override_reason` text DEFAULT NULL COMMENT 'Reason for admin override',\n  `is_locked` tinyint(1) DEFAULT '0' COMMENT 'Attendance locked status',\n  `locked_at` timestamp NULL DEFAULT NULL COMMENT 'When attendance was locked',\n  KEY `idx_session` (`attendance_session_id`),\n  KEY `idx_device` (`device_id`),\n  KEY `idx_is_locked` (`is_locked`),\n  KEY `idx_biometric_timestamp` (`biometric_timestamp`),\n  KEY `idx_stream` (`stream_id`),\n  KEY `idx_teacher` (`teacher_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


student_family_status	CREATE TABLE `student_family_status` (\n  `student_id` bigint NOT NULL,\n  `orphan_status_id` tinyint DEFAULT NULL,\n  `primary_guardian_name` varchar(150) DEFAULT NULL,\n  `primary_guardian_contact` varchar(60) DEFAULT NULL,\n  `primary_guardian_occupation` varchar(120) DEFAULT NULL,\n  `father_name` varchar(150) DEFAULT NULL,\n  `father_living_status_id` tinyint DEFAULT NULL,\n  `father_occupation` varchar(120) DEFAULT NULL,\n  `father_contact` varchar(60) DEFAULT NULL,\n  `notes` text COLLATE utf8_general_ci DEFAULT NULL,\n  `updated_at` timestamp NULL DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


attendance_audit_logs	CREATE TABLE `attendance_audit_logs` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `entity_type` enum('daily_attendance','manual_entry','device','rule') COLLATE utf8mb4_unicode_ci NOT NULL,\n  `entity_id` bigint NOT NULL,\n  `change_type` enum('create','update','delete','process') COLLATE utf8mb4_unicode_ci NOT NULL,\n  `user_id` bigint DEFAULT NULL,\n  `user_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `user_agent` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `old_values` json DEFAULT NULL,\n  `new_values` json DEFAULT NULL,\n  `change_summary` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `timestamp` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_entity` (`entity_type`,`entity_id`),\n  KEY `idx_user_id` (`user_id`),\n  KEY `idx_timestamp` (`timestamp`),\n  KEY `idx_change_type` (`change_type`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


expenditures	CREATE TABLE `expenditures` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `category_id` bigint NOT NULL,\n  `wallet_id` bigint DEFAULT NULL,\n  `amount` decimal(14,2) NOT NULL,\n  `description` text NOT NULL,\n  `vendor_name` varchar(150) DEFAULT NULL,\n  `vendor_contact` varchar(100) DEFAULT NULL,\n  `invoice_number` varchar(100) DEFAULT NULL,\n  `receipt_url` varchar(255) DEFAULT NULL,\n  `expense_date` date DEFAULT NULL,\n  `status` enum('pending','approved','paid','cancelled') DEFAULT 'pending',\n  `approved_by` bigint DEFAULT NULL,\n  `approved_at` timestamp NULL DEFAULT NULL,\n  `created_by` bigint DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_expenditures_school` (`school_id`),\n  KEY `idx_expenditures_category` (`category_id`),\n  KEY `idx_expenditures_wallet` (`wallet_id`),\n  KEY `idx_expenditures_date` (`expense_date`),\n  KEY `idx_expenditures_status` (`status`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Expenditure tracking for school expenses'


orphan_statuses	CREATE TABLE `orphan_statuses` (\n  `id` tinyint NOT NULL,\n  `code` varchar(20) NOT NULL,\n  `label` varchar(50) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


student_fee_items	CREATE TABLE `student_fee_items` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `student_id` bigint NOT NULL,\n  `section_id` bigint DEFAULT NULL,\n  `academic_year` varchar(9) DEFAULT NULL,\n  `fee_structure_id` bigint DEFAULT NULL,\n  `fee_type` varchar(50) DEFAULT NULL,\n  `due_date` date DEFAULT NULL,\n  `late_fee` decimal(14,2) DEFAULT '0.00',\n  `status` enum('pending','partial','paid','overdue','waived') DEFAULT 'pending',\n  `waived_by` bigint DEFAULT NULL,\n  `waived_reason` text COLLATE utf8_general_ci DEFAULT NULL,\n  `approved_by` bigint DEFAULT NULL,\n  `approved_at` timestamp NULL DEFAULT NULL,\n  `last_payment_date` timestamp NULL DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `term_id` bigint NOT NULL,\n  `item` varchar(120) NOT NULL,\n  `amount` decimal(14,2) NOT NULL,\n  `discount` decimal(14,2) DEFAULT '0.00',\n  `paid` decimal(14,2) DEFAULT '0.00',\n  `balance` decimal(14,2) GENERATED ALWAYS AS (((`amount` - `discount`) - `paid`)) STORED,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_sfi_student` (`student_id`),\n  KEY `idx_sfi_status` (`status`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


attendance_users	CREATE TABLE `attendance_users` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `username` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `first_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `last_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `role` enum('admin','director','teacher','parent','student','staff') COLLATE utf8mb4_unicode_ci DEFAULT 'staff',\n  `is_active` tinyint(1) DEFAULT '1',\n  `email_verified` tinyint(1) DEFAULT '0',\n  `last_login_at` timestamp NULL DEFAULT NULL,\n  `last_login_ip` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `password_changed_at` timestamp NULL DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `email` (`email`),\n  UNIQUE KEY `username` (`username`),\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_email` (`email`),\n  KEY `idx_role` (`role`),\n  KEY `idx_is_active` (`is_active`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


balance_reminders	CREATE TABLE `balance_reminders` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `student_id` bigint NOT NULL,\n  `term_id` bigint NOT NULL,\n  `reminder_type` enum('email','sms','both') DEFAULT 'both',\n  `threshold_amount` decimal(14,2) DEFAULT NULL,\n  `message` text DEFAULT NULL,\n  `sent_at` timestamp NULL DEFAULT NULL,\n  `status` enum('pending','sent','failed') DEFAULT 'pending',\n  `response_data` json DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_reminders_school` (`school_id`),\n  KEY `idx_reminders_student` (`student_id`),\n  KEY `idx_reminders_status` (`status`),\n  KEY `idx_reminders_sent` (`sent_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Balance reminder tracking'


dahua_attendance_logs	CREATE TABLE `dahua_attendance_logs` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `device_id` bigint NOT NULL,\n  `student_id` bigint DEFAULT NULL,\n  `card_no` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `user_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `event_time` datetime NOT NULL,\n  `event_type` enum('Entry','Exit','Unknown') COLLATE utf8mb4_unicode_ci DEFAULT 'Entry',\n  `method` enum('fingerprint','card','face','password','unknown') COLLATE utf8mb4_unicode_ci DEFAULT 'unknown',\n  `status` enum('present','absent','late','processed') COLLATE utf8mb4_unicode_ci DEFAULT 'processed',\n  `raw_log_id` bigint DEFAULT NULL,\n  `matched_at` timestamp NULL DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_device` (`device_id`),\n  KEY `idx_student` (`student_id`),\n  KEY `idx_card` (`card_no`),\n  KEY `idx_event_time` (`event_time`),\n  KEY `idx_created` (`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Normalized Dahua attendance logs'


fee_invoices	CREATE TABLE `fee_invoices` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `invoice_no` varchar(50) NOT NULL,\n  `student_id` bigint NOT NULL,\n  `academic_year_id` bigint DEFAULT NULL,\n  `term_id` bigint DEFAULT NULL,\n  `fee_structure_id` bigint DEFAULT NULL,\n  `total_amount` decimal(14,2) DEFAULT '0.00',\n  `discount_amount` decimal(14,2) DEFAULT '0.00',\n  `waive_amount` decimal(14,2) DEFAULT '0.00',\n  `paid_amount` decimal(14,2) DEFAULT '0.00',\n  `balance_amount` decimal(14,2) DEFAULT '0.00',\n  `status` enum('draft','issued','partial','paid','overdue','cancelled') DEFAULT 'draft',\n  `issue_date` date DEFAULT NULL,\n  `due_date` date DEFAULT NULL,\n  `notes` text DEFAULT NULL,\n  `created_by` bigint DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_finv_school` (`school_id`),\n  KEY `idx_finv_student` (`student_id`),\n  KEY `idx_finv_status` (`status`),\n  KEY `idx_finv_no` (`invoice_no`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Fee invoices'


ledger	CREATE TABLE `ledger` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `wallet_id` bigint NOT NULL,\n  `category_id` bigint NOT NULL,\n  `tx_type` varchar(10) NOT NULL,\n  `amount` decimal(14,2) NOT NULL,\n  `reference` varchar(120) DEFAULT NULL,\n  `description` text COLLATE utf8_general_ci DEFAULT NULL,\n  `student_id` bigint DEFAULT NULL,\n  `staff_id` bigint DEFAULT NULL,\n  `created_by` bigint DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


ledger_entries	CREATE TABLE `ledger_entries` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `transaction_id` bigint NOT NULL,\n  `account_id` bigint NOT NULL,\n  `entry_date` date DEFAULT NULL,\n  `description` text DEFAULT NULL,\n  `debit_amount` decimal(14,2) DEFAULT '0.00',\n  `credit_amount` decimal(14,2) DEFAULT '0.00',\n  `balance_after` decimal(14,2) DEFAULT NULL,\n  `currency` varchar(10) DEFAULT 'TZS',\n  `reference_type` varchar(50) DEFAULT NULL,\n  `reference_id` bigint DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_lent_school` (`school_id`),\n  KEY `idx_lent_transaction` (`transaction_id`),\n  KEY `idx_lent_account` (`account_id`),\n  KEY `idx_lent_date` (`entry_date`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='General ledger entries'


promotion_audit_log	CREATE TABLE `promotion_audit_log` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `promotion_id` bigint DEFAULT NULL,\n  `student_id` bigint NOT NULL,\n  `action_type` enum('promoted','demoted','dropped','status_changed','criteria_applied','cancelled') NOT NULL,\n  `from_class_id` bigint DEFAULT NULL,\n  `to_class_id` bigint DEFAULT NULL,\n  `from_academic_year_id` bigint DEFAULT NULL,\n  `to_academic_year_id` bigint DEFAULT NULL,\n  `status_before` varchar(50) DEFAULT NULL,\n  `status_after` varchar(50) DEFAULT NULL,\n  `criteria_applied` json DEFAULT NULL,\n  `performed_by` bigint NOT NULL,\n  `reason` text DEFAULT NULL,\n  `ip_address` varchar(45) DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_student_id` (`student_id`),\n  KEY `idx_action_type` (`action_type`),\n  KEY `idx_performed_by` (`performed_by`),\n  KEY `idx_created_at` (`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=7


role_permissions	CREATE TABLE `role_permissions` (\n  `role_id` bigint NOT NULL,\n  `permission_id` bigint NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


streams	CREATE TABLE `streams` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `class_id` bigint NOT NULL,\n  `name` varchar(50) NOT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


student_fingerprints	CREATE TABLE `student_fingerprints` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `student_id` bigint NOT NULL,\n  `device_id` bigint DEFAULT NULL,\n  `finger_position` enum('thumb','index','middle','ring','pinky','unknown') COLLATE utf8mb4_unicode_ci DEFAULT 'unknown',\n  `hand` enum('left','right') COLLATE utf8mb4_unicode_ci DEFAULT 'right',\n  `template_data` longblob DEFAULT NULL,\n  `template_format` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `biometric_uuid` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `quality_score` int DEFAULT '0',\n  `enrollment_timestamp` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `is_active` tinyint(1) DEFAULT '1',\n  `status` enum('active','inactive','revoked') COLLATE utf8mb4_unicode_ci DEFAULT 'active',\n  `last_matched_at` timestamp NULL DEFAULT NULL,\n  `match_count` int DEFAULT '0',\n  `notes` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_student` (`student_id`),\n  KEY `idx_device` (`device_id`),\n  KEY `idx_status` (`status`),\n  KEY `idx_biometric_uuid` (`biometric_uuid`),\n  KEY `idx_student_device` (`student_id`,`device_id`),\n  KEY `fk_fingerprints_school` (`school_id`),\n  CONSTRAINT `student_fingerprints_ibfk_1` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `student_fingerprints_ibfk_2` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `student_fingerprints_ibfk_3` FOREIGN KEY (`device_id`) REFERENCES `biometric_devices` (`id`) ON DELETE SET NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Student biometric fingerprint credentials'


dahua_devices	CREATE TABLE `dahua_devices` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `device_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `device_code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `port` int DEFAULT '80',\n  `api_url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `username` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `password` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `device_type` enum('attendance','access_control','hybrid') COLLATE utf8mb4_unicode_ci DEFAULT 'attendance',\n  `protocol` enum('http','https') COLLATE utf8mb4_unicode_ci DEFAULT 'http',\n  `status` enum('active','inactive','offline','error') COLLATE utf8mb4_unicode_ci DEFAULT 'active',\n  `last_sync` timestamp NULL DEFAULT NULL,\n  `last_sync_status` enum('success','failed','pending') COLLATE utf8mb4_unicode_ci DEFAULT 'pending',\n  `last_error_message` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `auto_sync_enabled` tinyint(1) DEFAULT '1',\n  `sync_interval_minutes` int DEFAULT '15',\n  `late_threshold_minutes` int DEFAULT '30',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `device_code` (`device_code`),\n  UNIQUE KEY `unique_dahua_code` (`device_code`),\n  KEY `idx_school` (`school_id`),\n  KEY `idx_status` (`status`),\n  KEY `idx_ip` (`ip_address`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=4 COMMENT='Dahua biometric device configuration and settings'


dahua_raw_logs	CREATE TABLE `dahua_raw_logs` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `device_id` bigint NOT NULL,\n  `raw_data` text COLLATE utf8mb4_unicode_ci NOT NULL,\n  `record_count` int DEFAULT '0',\n  `parsed_successfully` tinyint(1) DEFAULT '0',\n  `parse_errors` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_device` (`device_id`),\n  KEY `idx_created` (`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Raw Dahua device logs storage'


dahua_sync_history	CREATE TABLE `dahua_sync_history` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `device_id` bigint NOT NULL,\n  `sync_type` enum('manual','scheduled','automatic') COLLATE utf8mb4_unicode_ci DEFAULT 'manual',\n  `records_fetched` int DEFAULT '0',\n  `records_processed` int DEFAULT '0',\n  `records_failed` int DEFAULT '0',\n  `status` enum('in_progress','success','failed','partial') COLLATE utf8mb4_unicode_ci DEFAULT 'in_progress',\n  `started_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `completed_at` timestamp NULL DEFAULT NULL,\n  `error_details` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_device` (`device_id`),\n  KEY `idx_started` (`started_at`),\n  KEY `idx_status` (`status`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Dahua device sync history tracking'


enrollments	CREATE TABLE `enrollments` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `student_id` bigint NOT NULL,\n  `class_id` bigint DEFAULT NULL,\n  `theology_class_id` bigint DEFAULT NULL,\n  `stream_id` bigint DEFAULT NULL,\n  `academic_year_id` bigint DEFAULT NULL,\n  `term_id` bigint DEFAULT NULL,\n  `status` varchar(20) DEFAULT 'active',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=750682


report_card_subjects	CREATE TABLE `report_card_subjects` (\n  `id` bigint NOT NULL,\n  `report_card_id` bigint NOT NULL,\n  `subject_id` bigint NOT NULL,\n  `total_score` decimal(5,2) DEFAULT NULL,\n  `grade` varchar(10) DEFAULT NULL,\n  `remarks` text COLLATE utf8_general_ci DEFAULT NULL,\n  `position` int DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


result_types	CREATE TABLE `result_types` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `name` varchar(120) NOT NULL,\n  `code` varchar(60) DEFAULT NULL,\n  `description` text COLLATE utf8_general_ci DEFAULT NULL,\n  `weight` decimal(5,2) DEFAULT NULL,\n  `deadline` varchar(255) DEFAULT NULL,\n  `status` varchar(20) DEFAULT 'active',\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


student_profiles	CREATE TABLE `student_profiles` (\n  `student_id` bigint NOT NULL,\n  `place_of_birth` varchar(150) DEFAULT NULL,\n  `place_of_residence` varchar(150) DEFAULT NULL,\n  `district_id` bigint DEFAULT NULL,\n  `nationality_id` int DEFAULT NULL,\n  `passport_document_id` bigint DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


student_requirements	CREATE TABLE `student_requirements` (\n  `id` bigint NOT NULL,\n  `student_id` bigint NOT NULL,\n  `term_id` bigint NOT NULL,\n  `requirement_id` bigint NOT NULL,\n  `brought` tinyint(1) DEFAULT '0',\n  `date_reported` date DEFAULT NULL,\n  `notes` text COLLATE utf8_general_ci DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


terms	CREATE TABLE `terms` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `school_id` int NOT NULL DEFAULT '1',\n  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `start_date` date NOT NULL,\n  `end_date` date NOT NULL,\n  `academic_year_id` int DEFAULT NULL,\n  `is_active` tinyint(1) DEFAULT '1',\n  `notes` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_academic_year_id` (`academic_year_id`),\n  KEY `idx_dates` (`start_date`,`end_date`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=4


feature_flags	CREATE TABLE `feature_flags` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `route_name` varchar(255) NOT NULL DEFAULT 'default',\n  `route_path` varchar(255) NOT NULL DEFAULT '/',\n  `label` varchar(255) NOT NULL DEFAULT 'Feature',\n  `flag_name` varchar(100) NOT NULL,\n  `flag_key` varchar(100) NOT NULL,\n  `description` text DEFAULT NULL,\n  `is_enabled` tinyint(1) DEFAULT '0',\n  `is_new` tinyint(1) DEFAULT '0',\n  `version_tag` varchar(50) DEFAULT 'v_current',\n  `category` varchar(100) DEFAULT 'general',\n  `priority` int DEFAULT '0',\n  `date_added` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `expires_at` timestamp NULL DEFAULT NULL,\n  `flag_type` enum('boolean','percentage','user_list','variant') DEFAULT 'boolean',\n  `variant_data` json DEFAULT NULL,\n  `rollout_percentage` int DEFAULT '0',\n  `enabled_users` json DEFAULT NULL,\n  `notes` text DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `uq_flag_school` (`school_id`,`flag_key`),\n  KEY `idx_flag_enabled` (`is_enabled`,`updated_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


living_statuses	CREATE TABLE `living_statuses` (\n  `id` tinyint NOT NULL,\n  `code` varchar(20) NOT NULL,\n  `label` varchar(50) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


mobile_money_transactions	CREATE TABLE `mobile_money_transactions` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `student_id` bigint DEFAULT NULL,\n  `transaction_type` enum('deposit','withdrawal','payment','refund') DEFAULT 'payment',\n  `provider` enum('mpesa','airtel','tigo','vodacom','other') DEFAULT 'mpesa',\n  `phone_number` varchar(20) DEFAULT NULL,\n  `amount` decimal(14,2) DEFAULT '0.00',\n  `currency` varchar(10) DEFAULT 'TZS',\n  `transaction_ref` varchar(100) DEFAULT NULL,\n  `conversation_id` varchar(100) DEFAULT NULL,\n  `original_transaction_id` varchar(100) DEFAULT NULL,\n  `transaction_date` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `status` enum('pending','processing','completed','failed','cancelled') DEFAULT 'pending',\n  `result_code` varchar(20) DEFAULT NULL,\n  `result_desc` text DEFAULT NULL,\n  `balance` decimal(14,2) DEFAULT NULL,\n  `receipt_url` varchar(255) DEFAULT NULL,\n  `metadata` json DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_momo_school` (`school_id`),\n  KEY `idx_momo_student` (`student_id`),\n  KEY `idx_momo_provider` (`provider`),\n  KEY `idx_momo_status` (`status`),\n  KEY `idx_momo_ref` (`transaction_ref`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Mobile money transaction tracking'


roles	CREATE TABLE `roles` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `name` varchar(80) NOT NULL,\n  `description` text COLLATE utf8_general_ci DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=11


students	CREATE TABLE `students` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `person_id` bigint NOT NULL,\n  `class_id` int DEFAULT NULL,\n  `theology_class_id` int DEFAULT NULL,\n  `admission_no` varchar(50) DEFAULT NULL,\n  `village_id` bigint DEFAULT NULL,\n  `admission_date` date DEFAULT NULL,\n  `status` varchar(20) DEFAULT 'active',\n  `promotion_status` enum('promoted','not_promoted','pending') DEFAULT 'pending',\n  `last_promoted_at` datetime DEFAULT NULL,\n  `previous_class_id` bigint DEFAULT NULL,\n  `previous_year_id` bigint DEFAULT NULL,\n  `notes` text COLLATE utf8_general_ci DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT NULL,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `fk_students_villages` (`village_id`),\n  KEY `idx_promotion_status` (`promotion_status`),\n  KEY `idx_last_promoted` (`last_promoted_at`),\n  KEY `idx_previous_class` (`previous_class_id`),\n  CONSTRAINT `fk_students_villages` FOREIGN KEY (`village_id`) REFERENCES `villages` (`id`) ON DELETE SET NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=810663


tahfiz_plans	CREATE TABLE `tahfiz_plans` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `book_id` bigint DEFAULT NULL,\n  `teacher_id` bigint NOT NULL,\n  `class_id` bigint DEFAULT NULL,\n  `stream_id` bigint DEFAULT NULL,\n  `group_id` bigint DEFAULT NULL,\n  `assigned_date` date NOT NULL,\n  `portion_text` varchar(255) NOT NULL,\n  `portion_unit` varchar(50) DEFAULT 'verse',\n  `expected_length` int DEFAULT NULL,\n  `type` varchar(20) NOT NULL DEFAULT 'tilawa',\n  `notes` text DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school_date` (`school_id`,`assigned_date`),\n  KEY `idx_teacher` (`teacher_id`),\n  KEY `idx_book_id` (`book_id`),\n  KEY `idx_group_id` (`group_id`),\n  KEY `idx_class_id` (`class_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


user_sessions	CREATE TABLE `user_sessions` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `user_id` bigint NOT NULL,\n  `session_token` varchar(255) NOT NULL,\n  `ip_address` varchar(45) DEFAULT NULL,\n  `user_agent` varchar(255) DEFAULT NULL,\n  `expires_at` timestamp NOT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `session_token` (`session_token`),\n  KEY `idx_user_id` (`user_id`),\n  KEY `idx_session_token` (`session_token`),\n  KEY `idx_expires_at` (`expires_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


villages	CREATE TABLE `villages` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `parish_id` bigint NOT NULL,\n  `name` varchar(255) NOT NULL,\n  `description` text DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `name` (`name`),\n  KEY `idx_villages_parish` (`parish_id`),\n  KEY `idx_villages_name` (`name`),\n  KEY `idx_villages_deleted` (`deleted_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Villages table for location hierarchy'


device_configs	CREATE TABLE `device_configs` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `device_name` varchar(100) NOT NULL DEFAULT 'Access Control Device',\n  `device_ip` varchar(50) NOT NULL,\n  `device_port` int DEFAULT '80',\n  `device_username` varchar(100) NOT NULL,\n  `device_password_encrypted` varchar(255) NOT NULL,\n  `device_serial_number` varchar(100) DEFAULT NULL,\n  `device_type` varchar(50) DEFAULT NULL,\n  `connection_status` enum('connected','disconnected','error') DEFAULT 'disconnected',\n  `last_connection_attempt` timestamp NULL DEFAULT NULL,\n  `last_successful_connection` timestamp NULL DEFAULT NULL,\n  `last_error_message` varchar(255) DEFAULT NULL,\n  `is_active` tinyint(1) DEFAULT '1',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `device_serial_number` (`device_serial_number`),\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_serial_number` (`device_serial_number`),\n  KEY `idx_connection_status` (`connection_status`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


fee_payments	CREATE TABLE `fee_payments` (\n  `id` bigint NOT NULL,\n  `student_id` bigint NOT NULL,\n  `fee_item_id` bigint DEFAULT NULL,\n  `term_id` bigint NOT NULL,\n  `multi_term_ids` json DEFAULT NULL,\n  `wallet_id` bigint NOT NULL,\n  `amount` decimal(14,2) NOT NULL,\n  `method` varchar(30) DEFAULT NULL,\n  `discount_type` enum('percentage','fixed') DEFAULT NULL,\n  `discount_reason` text COLLATE utf8_general_ci DEFAULT NULL,\n  `approved_by` bigint DEFAULT NULL,\n  `approved_at` timestamp NULL DEFAULT NULL,\n  `receipt_url` varchar(255) DEFAULT NULL,\n  `invoice_url` varchar(255) DEFAULT NULL,\n  `notes` text COLLATE utf8_general_ci DEFAULT NULL,\n  `paid_by` varchar(150) DEFAULT NULL,\n  `payer_contact` varchar(50) DEFAULT NULL,\n  `reference` varchar(120) DEFAULT NULL,\n  `receipt_no` varchar(40) DEFAULT NULL,\n  `payment_status` enum('pending','completed','failed','refunded') DEFAULT 'completed',\n  `gateway_reference` varchar(255) DEFAULT NULL,\n  `gateway_response` json DEFAULT NULL,\n  `mpesa_receipt` varchar(100) DEFAULT NULL,\n  `phone_number` varchar(20) DEFAULT NULL,\n  `ledger_id` bigint DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  KEY `idx_fp_student` (`student_id`),\n  KEY `idx_fp_status` (`payment_status`),\n  KEY `idx_fp_date` (`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


payroll_definitions	CREATE TABLE `payroll_definitions` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `name` varchar(120) NOT NULL,\n  `type` varchar(20) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


student_hafz_progress_summary	CREATE TABLE `student_hafz_progress_summary` (\n  `student_id` bigint NOT NULL,\n  `juz_memorized` int DEFAULT '0',\n  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


subcounties	CREATE TABLE `subcounties` (\n  `id` bigint NOT NULL,\n  `county_id` bigint NOT NULL,\n  `name` varchar(150) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


academic_years	CREATE TABLE `academic_years` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `name` varchar(20) NOT NULL,\n  `start_date` date DEFAULT NULL,\n  `end_date` date DEFAULT NULL,\n  `status` varchar(20) DEFAULT 'active'\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


tahfiz_seven_metrics	CREATE TABLE `tahfiz_seven_metrics` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `result_id` bigint NOT NULL,\n  `fluency_score` decimal(5,2) DEFAULT '0.00',\n  `accuracy_score` decimal(5,2) DEFAULT '0.00',\n  `tajweed_score` decimal(5,2) DEFAULT '0.00',\n  `consistency_score` decimal(5,2) DEFAULT '0.00',\n  `participation_score` decimal(5,2) DEFAULT '0.00',\n  `attitude_score` decimal(5,2) DEFAULT '0.00',\n  `improvement_score` decimal(5,2) DEFAULT '0.00',\n  `overall_score` decimal(5,2) DEFAULT '0.00',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `result_id` (`result_id`),\n  KEY `idx_school_id` (`school_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


daily_attendance	CREATE TABLE `daily_attendance` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `person_type` enum('student','teacher') COLLATE utf8mb4_unicode_ci NOT NULL,\n  `person_id` bigint NOT NULL,\n  `attendance_date` date NOT NULL,\n  `status` enum('present','late','absent','excused','on_leave','pending') COLLATE utf8mb4_unicode_ci DEFAULT 'pending',\n  `first_arrival_time` time DEFAULT NULL,\n  `last_departure_time` time DEFAULT NULL,\n  `arrival_device_id` bigint DEFAULT NULL,\n  `is_manual_entry` tinyint(1) DEFAULT '0',\n  `manual_entry_id` bigint DEFAULT NULL,\n  `is_late` tinyint(1) DEFAULT '0',\n  `late_minutes` int DEFAULT '0',\n  `late_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `excuse_type` enum('medical','parental','official','other','none') COLLATE utf8mb4_unicode_ci DEFAULT 'none',\n  `excuse_note` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `marking_rule_id` bigint DEFAULT NULL,\n  `processing_metadata` json DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `processed_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `uk_school_person_date` (`school_id`,`person_type`,`person_id`,`attendance_date`),\n  KEY `idx_school_date` (`school_id`,`attendance_date`),\n  KEY `idx_person` (`person_type`,`person_id`),\n  KEY `idx_status` (`status`),\n  KEY `idx_is_manual` (`is_manual_entry`),\n  KEY `idx_is_late` (`is_late`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


events	CREATE TABLE `events` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `title` varchar(200) NOT NULL,\n  `description` text COLLATE utf8_general_ci DEFAULT NULL,\n  `start_datetime` datetime NOT NULL,\n  `end_datetime` datetime NOT NULL,\n  `location` varchar(120) DEFAULT NULL,\n  `status` varchar(20) DEFAULT 'upcoming',\n  `created_by` bigint DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


manual_attendance_entries	CREATE TABLE `manual_attendance_entries` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `daily_attendance_id` bigint NOT NULL,\n  `person_type` enum('student','teacher') COLLATE utf8mb4_unicode_ci NOT NULL,\n  `person_id` bigint NOT NULL,\n  `attendance_date` date NOT NULL,\n  `status` enum('present','late','absent','excused','on_leave') COLLATE utf8mb4_unicode_ci NOT NULL,\n  `arrival_time` time DEFAULT NULL,\n  `departure_time` time DEFAULT NULL,\n  `reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `notes` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `override_type` enum('status_change','new_entry','excuse_update','time_correction') COLLATE utf8mb4_unicode_ci DEFAULT 'status_change',\n  `previous_status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `previous_arrival_time` time DEFAULT NULL,\n  `previous_departure_time` time DEFAULT NULL,\n  `created_by_user_id` bigint DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `deleted_by_user_id` bigint DEFAULT NULL,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_daily_attendance` (`daily_attendance_id`),\n  KEY `idx_person` (`person_type`,`person_id`),\n  KEY `idx_attendance_date` (`attendance_date`),\n  KEY `idx_created_by` (`created_by_user_id`),\n  KEY `idx_created_at` (`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


attendance_rules	CREATE TABLE `attendance_rules` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `rule_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\n  `rule_description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `arrival_start_time` time DEFAULT NULL,\n  `arrival_end_time` time DEFAULT NULL,\n  `late_threshold_minutes` int DEFAULT '15',\n  `absence_cutoff_time` time DEFAULT NULL,\n  `closing_time` time DEFAULT NULL,\n  `applies_to` enum('students','teachers','all') COLLATE utf8mb4_unicode_ci DEFAULT 'students',\n  `applies_to_classes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `auto_excuse_after_days` int DEFAULT '0',\n  `ignore_duplicate_scans_within_minutes` int DEFAULT '2',\n  `is_active` tinyint(1) DEFAULT '1',\n  `effective_date` date DEFAULT NULL,\n  `end_date` date DEFAULT NULL,\n  `priority` int DEFAULT '100',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_is_active` (`is_active`),\n  KEY `idx_effective_date` (`effective_date`),\n  KEY `idx_priority` (`priority`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=2


notifications	CREATE TABLE `notifications` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `actor_user_id` bigint DEFAULT NULL,\n  `action` varchar(120) NOT NULL,\n  `entity_type` varchar(50) DEFAULT NULL,\n  `entity_id` bigint DEFAULT NULL,\n  `title` varchar(255) DEFAULT NULL,\n  `message` text DEFAULT NULL,\n  `metadata` json DEFAULT NULL,\n  `priority` enum('low','normal','high','critical') DEFAULT 'normal',\n  `channel` varchar(50) DEFAULT 'in_app',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `read_count` int DEFAULT '0',\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_notifications_school_created` (`school_id`,`created_at`),\n  KEY `idx_notifications_actor` (`actor_user_id`),\n  KEY `idx_notifications_action` (`action`),\n  KEY `idx_notifications_entity` (`entity_type`,`entity_id`),\n  KEY `idx_notifications_priority` (`priority`,`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Core notifications storage'


permissions	CREATE TABLE `permissions` (\n  `id` bigint NOT NULL,\n  `code` varchar(120) NOT NULL,\n  `description` text COLLATE utf8_general_ci DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


requirements_master	CREATE TABLE `requirements_master` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `name` varchar(120) NOT NULL,\n  `description` text COLLATE utf8_general_ci DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


attendance_logs	CREATE TABLE `attendance_logs` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `device_id` bigint NOT NULL,\n  `device_user_id` int NOT NULL,\n  `scan_timestamp` timestamp NOT NULL,\n  `received_timestamp` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `verification_status` enum('success','failed','unknown') COLLATE utf8mb4_unicode_ci DEFAULT 'success',\n  `biometric_quality` int DEFAULT NULL,\n  `device_log_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `device_sync_count` int DEFAULT '1',\n  `processing_status` enum('pending','processed','error','duplicate') COLLATE utf8mb4_unicode_ci DEFAULT 'pending',\n  `process_error_message` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `mapped_device_user_id` bigint DEFAULT NULL,\n  `is_duplicate` tinyint(1) DEFAULT '0',\n  `duplicate_of_log_id` bigint DEFAULT NULL,\n  `raw_data` json DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `uk_school_duplicate` (`school_id`,`device_id`,`device_user_id`,`scan_timestamp`,`device_log_id`),\n  KEY `idx_school_scan` (`school_id`,`scan_timestamp`),\n  KEY `idx_device_user_scan` (`device_user_id`,`scan_timestamp`),\n  KEY `idx_processing_status` (`processing_status`),\n  KEY `idx_received_timestamp` (`received_timestamp`),\n  KEY `idx_scan_timestamp` (`scan_timestamp`),\n  KEY `idx_device_id` (`device_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


attendance_reports	CREATE TABLE `attendance_reports` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `report_type` enum('daily_summary','weekly_trend','monthly_summary','class_analysis','student_profile','period_comparison') COLLATE utf8mb4_unicode_ci DEFAULT 'daily_summary',\n  `date_from` date DEFAULT NULL,\n  `date_to` date DEFAULT NULL,\n  `class_id` bigint DEFAULT NULL,\n  `stream_id` bigint DEFAULT NULL,\n  `academic_year_id` bigint DEFAULT NULL,\n  `report_data` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `generated_by` bigint DEFAULT NULL,\n  `generated_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `expires_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school` (`school_id`),\n  KEY `idx_generated_at` (`generated_at`),\n  KEY `idx_report_type` (`report_type`),\n  CONSTRAINT `attendance_reports_ibfk_1` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Cached attendance reports'


class_subjects	CREATE TABLE `class_subjects` (\n  `id` bigint NOT NULL,\n  `class_id` bigint NOT NULL,\n  `subject_id` bigint NOT NULL,\n  `teacher_id` bigint DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


districts	CREATE TABLE `districts` (\n  `id` bigint NOT NULL,\n  `name` varchar(150) NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


documents	CREATE TABLE `documents` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `owner_type` varchar(30) NOT NULL,\n  `owner_id` bigint NOT NULL,\n  `document_type_id` bigint NOT NULL,\n  `file_name` varchar(200) NOT NULL,\n  `file_url` varchar(255) NOT NULL,\n  `mime_type` varchar(100) DEFAULT NULL,\n  `file_size` bigint DEFAULT NULL,\n  `issued_by` varchar(150) DEFAULT NULL,\n  `issue_date` date DEFAULT NULL,\n  `notes` text COLLATE utf8_general_ci DEFAULT NULL,\n  `uploaded_by` bigint DEFAULT NULL,\n  `uploaded_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


notification_queue	CREATE TABLE `notification_queue` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `notification_id` bigint NOT NULL,\n  `recipient_user_id` bigint DEFAULT NULL,\n  `channel` varchar(50) DEFAULT 'in_app',\n  `attempts` int DEFAULT '0',\n  `max_attempts` int DEFAULT '3',\n  `last_attempt_at` timestamp NULL DEFAULT NULL,\n  `next_attempt_at` timestamp NULL DEFAULT NULL,\n  `status` enum('pending','sent','failed','cancelled') DEFAULT 'pending',\n  `payload` json DEFAULT NULL,\n  `error_message` text DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_queue_status` (`status`,`next_attempt_at`),\n  KEY `idx_queue_recipient` (`recipient_user_id`),\n  KEY `idx_queue_notification` (`notification_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Notification delivery queue'


people	CREATE TABLE `people` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint DEFAULT NULL,\n  `first_name` varchar(100) NOT NULL,\n  `last_name` varchar(100) NOT NULL,\n  `other_name` varchar(100) DEFAULT NULL,\n  `gender` varchar(15) DEFAULT NULL,\n  `date_of_birth` date DEFAULT NULL,\n  `phone` varchar(30) DEFAULT NULL,\n  `email` varchar(150) DEFAULT NULL,\n  `address` text COLLATE utf8_general_ci DEFAULT NULL,\n  `photo_url` varchar(255) DEFAULT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT NULL,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=900682


promotion_criteria	CREATE TABLE `promotion_criteria` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL DEFAULT '1',\n  `name` varchar(100) NOT NULL,\n  `description` text DEFAULT NULL,\n  `criteria_type` enum('marks','average','attendance','conduct','custom') DEFAULT 'marks',\n  `condition_json` json NOT NULL,\n  `is_active` tinyint(1) DEFAULT '1',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_is_active` (`is_active`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


tahfiz_attendance	CREATE TABLE `tahfiz_attendance` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `student_id` bigint NOT NULL,\n  `group_id` bigint NOT NULL,\n  `date` date NOT NULL,\n  `status` enum('present','absent','late','excused') DEFAULT 'present',\n  `remarks` text COLLATE utf8_general_ci DEFAULT NULL,\n  `recorded_by` bigint DEFAULT NULL,\n  `recorded_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


tahfiz_books	CREATE TABLE `tahfiz_books` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `title` varchar(100) NOT NULL,\n  `description` text COLLATE utf8_general_ci DEFAULT NULL,\n  `total_units` int DEFAULT NULL,\n  `unit_type` varchar(50) DEFAULT 'verse',\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


attendance_processing_queue	CREATE TABLE `attendance_processing_queue` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `school_id` bigint NOT NULL,\n  `job_type` enum('process_device_logs','calculate_daily_attendance','recalculate_date_range','rule_recalculation','sync_device') COLLATE utf8mb4_unicode_ci NOT NULL,\n  `parameters` json DEFAULT NULL,\n  `status` enum('queued','processing','completed','failed','retrying') COLLATE utf8mb4_unicode_ci DEFAULT 'queued',\n  `priority` int DEFAULT '0',\n  `attempted_count` int DEFAULT '0',\n  `max_attempts` int DEFAULT '3',\n  `result` json DEFAULT NULL,\n  `error_message` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  `error_details` json DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `started_at` timestamp NULL DEFAULT NULL,\n  `completed_at` timestamp NULL DEFAULT NULL,\n  `next_retry_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  KEY `idx_school_status` (`school_id`,`status`),\n  KEY `idx_status` (`status`),\n  KEY `idx_priority` (`priority`),\n  KEY `idx_created_at` (`created_at`),\n  KEY `idx_next_retry` (`next_retry_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


user_notifications	CREATE TABLE `user_notifications` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `notification_id` bigint NOT NULL,\n  `user_id` bigint NOT NULL,\n  `school_id` bigint DEFAULT NULL,\n  `is_read` tinyint(1) DEFAULT '0',\n  `is_archived` tinyint(1) DEFAULT '0',\n  `channel` varchar(50) DEFAULT 'in_app',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `read_at` timestamp NULL DEFAULT NULL,\n  `archived_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,\n  UNIQUE KEY `uq_user_notification` (`notification_id`,`user_id`),\n  KEY `idx_user_notifications_user` (`user_id`,`is_read`,`is_archived`),\n  KEY `idx_user_notifications_school` (`school_id`,`user_id`),\n  KEY `idx_user_notifications_created` (`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Per-user notification state'


departments	CREATE TABLE `departments` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `name` varchar(120) NOT NULL,\n  `head_staff_id` bigint DEFAULT NULL,\n  `description` text COLLATE utf8_general_ci DEFAULT NULL,\n  `budget` decimal(14,2) DEFAULT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  KEY `idx_school_id` (`school_id`),\n  KEY `idx_name` (`name`),\n  KEY `idx_head_staff_id` (`head_staff_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


fee_structures	CREATE TABLE `fee_structures` (\n  `id` bigint NOT NULL,\n  `school_id` bigint NOT NULL,\n  `class_id` bigint NOT NULL,\n  `section_id` bigint DEFAULT NULL,\n  `term_id` bigint NOT NULL,\n  `academic_year` varchar(9) DEFAULT NULL,\n  `item` varchar(120) NOT NULL,\n  `fee_type` enum('tuition','uniform','transport','boarding','examination','activity','books','other') DEFAULT 'tuition',\n  `is_mandatory` tinyint(1) DEFAULT '1',\n  `amount` decimal(14,2) NOT NULL,\n  `description` text COLLATE utf8_general_ci DEFAULT NULL,\n  `due_date` date DEFAULT NULL,\n  `late_fee_amount` decimal(14,2) DEFAULT '0.00',\n  `is_active` tinyint(1) DEFAULT '1',\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  KEY `idx_fs_class` (`class_id`),\n  KEY `idx_fs_year` (`academic_year`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin


SET FOREIGN_KEY_CHECKS=1;
